{% set name = "imbalanced-learn" %}
{% set version = "0.3.2" %}
{% set sha256 = "53a4cb0d3adcfda2140a7152e46a2c5d6e9bce71da010b2962090cbbf5d4577e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9
    - scipy
    - scikit-learn 0.19.*

  run:
    - python
    - numpy >=1.9
    - scipy
    - scikit-learn 0.19.*

test:
  imports:
    - imblearn

about:
  home: https://github.com/scikit-learn-contrib/imbalanced-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python module to balance data set using under- and over-sampling'
  description: |
    imbalanced-learn is a python package offering a number of re-sampling
    techniques commonly used in datasets showing strong between-class imbalance.
    It is compatible with scikit-learn and is part of scikit-learn-contrib
    projects.
  doc_url: http://contrib.scikit-learn.org/imbalanced-learn
  dev_url: https://github.com/scikit-learn-contrib/imbalanced-learn

extra:
  recipe-maintainers:
    - glemaitre
