{% set name = "imbalanced-learn" %}
{% set version = "0.7.0" %}
{% set sha256 = "da59de0d1c0fa66f62054dd9a0a295a182563aa1abbb3bf9224a3678fcfe8fa4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3
    - setuptools
    - pip
  host:
    - python >=3
    - pip
  run:
    - python >=3
    # scipy needs a hotfix for upper-bound on numpy 
    # remove the 1.23.0 upperbound when fixed
    - numpy >=1.14.6,<1.23.0
    - scipy >=1.3.2
    - scikit-learn >=1.0.1
    - joblib >=0.11


test:
  requires:
    - pytest >=5.0.1
    - pytest-timeout
    - statsmodels
  imports:
    - imblearn
  # tests are broken in 0.7.0
  #commands:
  #  - pytest --timeout 300 --verbose --pyargs imblearn

about:
  home: https://github.com/scikit-learn-contrib/imbalanced-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python module to balance data set using under- and over-sampling
  description: |
    imbalanced-learn is a python package offering a number of re-sampling
    techniques commonly used in datasets showing strong between-class imbalance.
    It is compatible with scikit-learn and is part of scikit-learn-contrib
    projects.
  doc_url: http://imbalanced-learn.org/en/stable/
  dev_url: https://github.com/scikit-learn-contrib/imbalanced-learn

extra:
  recipe-maintainers:
    - glemaitre
  anaconda-services:
    comment: "Built as dependency for customer: see https://anaconda.zendesk.com/agent/tickets/26940"
    recipe_maintainers:
      - bkreider

