travis:
  secure:
    BINSTAR_TOKEN: H4LzSqMkkaREE+LHGCEqvUxsuQ4jZtOr4f+gvM7N3l8GFCFXIkO850ttjzI3mT+DImCSzilnUUNanjIGzOOkN4hcQho0asiOK8tSUfutSTzi54wlVQbTpPrBUqVLqF+mKBvY2MBBZcDAohP68VO96AHphWBtH4tEhSn9qPWB8EIJdD2XLtvi+SxVAUbajl6oyN+fkByn6ykQvY9nRPLW7qZpwcN0l2AU+J+mdHWARanMUqAgvF69rsAriwZgbdrLDn6VqcQ4uPFn89OQaeQo+uhHMiinrk9wHB1q8Yq1W0lhae7ZO1+nIK6XXgbO/oOtrzGNsIMB6nReuJvcGZTd78E3rS6UAuUCJTQxyoNDk/WwLtGS+Ud+vXo+itfN+v7A9CzvgrRSgFdTSm2/AXoiWCk6IP3LLn/gSCa6DTTrqTIk067ONtJsLizVrhBLsizNWD+m3WUnPeKjjOYIOfMu9weTq4uzAqQta3msspn2lPIB9CDtNL6VAr1krX/+5fCKcjb+g6WIp6xbjDUddJvEgxqTXD5SV2c8fWjJnY8dTzeKD3XvAlbwtveTGvmeA3sLXYyygKji6NgV5PjkUWiZEkl5+oS55fmgecHHvoBKRsGtBqmTftSJkR/5wwXqfQIcnkS4XALW8PNek1MYtHJRBtDpmpJuOZ3oZ159F4zRArI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
