travis:
  secure:
    BINSTAR_TOKEN: bxIY7q4jKUNAe8MerlEoUsHJAm0jQp1n0Bk2m7XG4deyxradPe4v1+EGCBZks7TNZ+ndZh7f/nGp6LJIwF3nuP2x/P9ykCFs/iaf4zKS3lX+11RQSBEtNmjMPPOVVtl5raxaWJ6TM9scE9WWnvLlVJePZjKslXRo7KwT36RlC6wlLoflYTkJLskhPmLtD0BSugmvZoDTGua1fouXWl7QSmbU8asW16iu4PXUB9wyDEnTGoml/WGu4d7PiypdyjPEl0osQ3wZGhAP7qDE2qR9ariJyxvSMp92SeqMCmmxAh4oS3ffpC02sitxoXTY7o3W48rXPI9j2uD//31VlDYJEAaFYhV1vjroTFWe+2B1LbikPOFKLKYtoqAMsF27Qzrk7QVhpl/ddmAXk+PmlhbCvWCnv0jMUJwQ08Xzy4x5mIUAxxVS4ms+SiMBTj5sRqQG149qz/VuqgTuMsIKKGpRANK0bMAQ9iM+x+uiKgsc5wGpmY1ka4SMNZ4UEoweU4VBRteq2pu4cuftVgcyeiGxTTYKzEEt9q5YQuqKTWG1LOZuo32VCxUOe6GKu/PUWoKE0ZuzrM+cxG2VxbeRIPz0bg8/JNsb0Am22QM6gYAw9p2DbIF6DTJfbNma91yi85QF5rTB3YPp9EHdS6AeeSawXDGPolVnINJ65FVyAhtxxMA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
